[versions]
# Base
agp = "8.11.2"
kotlin = "2.2.21"
core-ktx = "1.17.0"
junit = "4.13.2"
junit-version = "1.3.0"
espresso-core = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
serialization-json = "1.9.0"
dagger-hilt = "2.57.2"
hilt-navigation = "1.3.0"
ksp = "2.3.2"
napier = "2.7.1"
javapoet = "1.13.0"
material3 = "1.4.0"

# Compose
compose-bom = "2025.11.00"
compose-vm = "2.9.4"
compose-activity = "1.11.0"
nav3Core = "1.0.1"
lifecycleViewmodelNav3 = "2.10.0"
material3AdaptiveNav3 = "1.3.0-alpha08"
compose-animations = "1.9.4"
compose-coil = "3.3.0"
lifecycle-runtime-ktx = "2.9.4"
compose = "1.6.10"
compose-icons = "1.7.7"
compose-cloudy = "0.5.0"
compose-shimmer = "1.3.3"

[libraries]
gradleplugin-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradleplugin-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose" }
gradleplugin-composeCompiler = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "compose" }
gradleplugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

# === Base === #
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization-json" }
log-napier = { group = "io.github.aakira", name = "napier", version.ref = "napier" }
javapoet = { group = "com.squareup", name = "javapoet", version.ref = "javapoet" }

# === Compose === #
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-animations = { group = "androidx.compose.animation", name = "animation", version.ref = "compose-animations" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
compose-lifecycle-vm = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "compose-vm" }
compose-coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "compose-coil" }
compose-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose-icons" }
compose-cloudy = { module = "com.github.skydoves:cloudy", version.ref = "compose-cloudy" }
compose-shimmer = { group = "com.valentinilk.shimmer", name = "compose-shimmer", version.ref = "compose-shimmer" }

# Navigation 3 libraries
compose-navigation-core = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
compose-navigation-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
compose-navigation-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }
compose-navigation-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "material3AdaptiveNav3" }

# Compose test and debug #
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

# === DI === #
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger-hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "dagger-hilt" }
hilt-compose-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
serialization-json = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }

# Conventions
convention-shared = { id = "dot.adun.convention.shared" }
convention-compose = { id = "dot.adun.convention.compose" }
convention-app = { id = "dot.adun.convention.app" }

[bundles]
hilt = ["hilt", "hilt-compose-navigation"]
compose = ["compose-bom", "compose-activity", "compose-animations", "compose-coil", "compose-foundation", "compose-lifecycle-vm", "compose-material3", "compose-ui", "compose-ui-graphics", "compose-ui-tooling-preview"]
compose-debug = ["compose-ui-tooling", "androidx-ui-test-manifest", "androidx-ui-test-junit4"]
compose-android-test = ["androidx-junit", "androidx-espresso-core"]
